* Installation
  Clone this repo into ~/.emacs.d/ and launch Emacs.
  #+BEGIN_SRC bash
  git clone https://github.com/jenterkin/emacs-config.git ~/.emacs.d/
  #+END_SRC

* Setup use-package
** Install use-package
  #+BEGIN_SRC emacs-lisp
  (require 'package)
  (setq package-enable-at-startup nil)
  (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
  (package-initialize)

  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))

  (eval-when-compile
    (require 'use-package))
  #+END_SRC

** Always make sure pacakges are installed
   #+BEGIN_SRC emacs-lisp
   (setq use-package-always-ensure t)
   #+END_SRC

* Appearance
** Font
   Use the font `Source Code Pro` with a size of 12px.
   #+BEGIN_SRC emacs-lisp
     (add-to-list 'default-frame-alist '(font . "Source Code Pro-10"))
     (set-face-attribute 'default t :font "Source Code Pro-10")
   #+END_SRC

** Color Theme
   [[https://github.com/hlissner/emacs-doom-themes][GitHub Page]]
    #+BEGIN_SRC emacs-lisp
      (use-package doom-themes
	:init
	(load-theme 'doom-nord t))
      (setq doom-themes-enable-bold t)
      (doom-themes-org-config)
      (doom-themes-neotree-config)
    #+END_SRC

** Visually distinguise windows with files open
   For instance, if you have a file open with a magit status window open, the file window will be brighter.
   #+BEGIN_SRC emacs-lisp
     (use-package solaire-mode
       :ensure t
       :config
       (solaire-global-mode +1)
       (solaire-mode-swap-bg))
   #+END_SRC

** Line numbers
   Show relative line numbers
   #+BEGIN_SRC emacs-lisp
     (setq display-line-numbers-type 'relative)
     ; Only show line numbers in buffers with code
     (add-hook 'prog-mode-hook #'display-line-numbers-mode)
   #+END_SRC

** Disable UI elements
*** Menu bar
    #+BEGIN_SRC emacs-lisp
    (menu-bar-mode -1)
    #+END_SRC

*** Tool bar
    #+BEGIN_SRC emacs-lisp
    (tool-bar-mode -1)
    #+END_SRC

*** Scroll bar
    #+BEGIN_SRC emacs-lisp
    (toggle-scroll-bar -1)
    #+END_SRC

** Icons
   All The Icons
   [[https://github.com/domtronn/all-the-icons.el][GitHub Page]]
   #+BEGIN_SRC emacs-lisp
   (use-package all-the-icons
     :ensure t)
   ; Run the following after initial install:
   ; M-x all-the-icons-install-fonts
   #+END_SRC

** Highlight current line
   #+BEGIN_SRC emacs-lisp
     (global-hl-line-mode 1)
   #+END_SRC

* Markdown
  #+BEGIN_SRC emacs-lisp
    (use-package markdown-mode
      :ensure t
      :commands (markdown-mode gfm-mode)
      :mode (("README\\.md\\'" . gfm-mode)
	     ("\\.md\\'" . markdown-mode)
	     ("\\.markdown\\'" . markdown-mode))
      :init (setq markdown-command "pandoc"))
  #+END_SRC

* Eyebrows
  #+BEGIN_SRC emacs-lisp
    (use-package eyebrowse
      :ensure t
      :init
      (eyebrowse-mode 1))
  #+END_SRC

* Helm
  [[https://github.com/emacs-helm/helm][GitHub Page]]
  #+BEGIN_SRC emacs-lisp
    (use-package helm)
  #+END_SRC

** Always open on bottom
   [[https://www.reddit.com/r/emacs/comments/345vtl/make_helm_window_at_the_bottom_without_using_any/][Found on reddit]]
   #+BEGIN_SRC emacs-lisp
     (add-to-list 'display-buffer-alist
		  `(,(rx bos "*helm" (* not-newline) "*" eos)
		    (display-buffer-in-side-window)
		    (inhibit-same-window . t)
		    (window-height . 0.4)))
   #+END_SRC

** Additional Pacakges
*** helm-projectile
   [[https://github.com/bbatsov/helm-projectile][GitHub Page]]
   #+BEGIN_SRC emacs-lisp
     (use-package helm-projectile)
   #+END_SRC

*** helm-ag
   [[https://github.com/syohex/emacs-helm-ag][GitHub Page]]
   #+BEGIN_SRC emacs-lisp
     (use-package helm-ag)
   #+END_SRC

* Neotree
  [[https://github.com/jaypei/emacs-neotree][GitHub Page]]
  #+BEGIN_SRC emacs-lisp
    (use-package neotree
      :ensure t)
  #+END_SRC

* LSP
  #+BEGIN_SRC emacs-lisp
    (use-package lsp-mode
      :ensure t
      :init
      (setq lsp-enable-snippet nil)
      :config
      (add-hook 'python-mode-hook 'lsp)
      (add-hook 'rust-mode-hook 'lsp))

    (use-package lsp-ui :commands lsp-ui-mode)
    (use-package company-lsp :commands company-lsp)
    (use-package helm-lsp :commands helm-lsp-workspace-symbol)
    (use-package lsp-treemacs :commands lsp-treemacs-errors-list)
    (use-package dap-mode)
  #+END_SRC

* Org Mode
** Require package
   #+BEGIN_SRC emacs-lisp
   (require 'org)
   #+END_SRC

** Show line numbers
   #+BEGIN_SRC emacs-lisp
     (add-hook 'org-mode-hook #'display-line-numbers-mode)
   #+END_SRC

** Make it fancy
*** org-bullets
    #+BEGIN_SRC emacs-lisp
    (use-package org-bullets
      :config
      (progn
        (require 'org-bullets)
        (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))))
    #+END_SRC

** Make it evil
   #+BEGIN_SRC emacs-lisp
   (use-package evil-org
     :defer t
     :config
     (progn
       (add-hook 'org-mode-hook 'evil-org-mode)
	    (evil-org-set-key-theme '(navigation insert textobjects additional calendar))
	    (require 'evil-org-agenda)
   	 (evil-org-agenda-set-keys)
	 (define-key evil-normal-state-map (kbd ">>") 'org-metaright)))
   #+END_SRC

** Exporter Packages
*** htmlize
    #+BEGIN_SRC emacs-lisp
    (use-package htmlize)
    #+END_SRC

*** ox-twbs
    #+BEGIN_SRC emacs-lisp
    (use-package ox-twbs)
    #+END_SRC

* Evil Mode
** Set up leader
   =evil-leader= must be enabled before =evil-mode=, otherwise it won't be enabled for initial buffers.
   #+BEGIN_SRC emacs-lisp
   (use-package evil-leader
     :config
     (global-evil-leader-mode)
     (evil-leader/set-leader "<SPC>"))
   #+END_SRC

*** Set leader to <SPC>
    #+BEGIN_SRC emacs-lisp
    ; (evil-leader/set
    #+END_SRC

** Install evil-mode
   #+BEGIN_SRC emacs-lisp
   (use-package evil
     :init
     (progn
       (setq evil-default-cursor t)
       (evil-mode 1)))
   #+END_SRC

** jj for <Esc>
   #+BEGIN_SRC emacs-lisp
     (use-package key-chord
       :config
       (setq key-chord-two-keys-delay 0.5)
       (key-chord-define evil-insert-state-map "jj" 'evil-normal-state)
       (key-chord-mode 1))
   #+END_SRC

* Languages
** Go
*** go-mode
    Major version for Go
    [[https://github.com/dominikh/go-mode.el][GitHub Page]]
    #+BEGIN_SRC emacs-lisp
    (use-package go-mode)
    #+END_SRC

* Which Key
  [[https://github.com/justbur/emacs-which-key][GitHub page]]
  Show keybindings for current incomplete command.
#+BEGIN_SRC emacs-lisp
(use-package which-key
  :config
  (progn
    (which-key-mode 1)
    (setq which-key-allow-evil-operators 1)
    (setq which-key-idle-delay 0.25)))
(provide 'setup-which-key)
#+END_SRC

* Docker
** Packages
*** dockerfile-mode
    Major mode for Dockerfiles
    [[https://github.com/spotify/dockerfile-mode][GitHub Page]]
    #+BEGIN_SRC emacs-lisp
    (use-package dockerfile-mode)
    #+END_SRC

*** docker
    Control Docker from Emacs
    [[https://github.com/Silex/docker.el][GitHub Page]]
    #+BEGIN_SRC emacs-lisp
    (use-package docker
      :bind ("C-c d" . docker))
    #+END_SRC

* YAML
** Packages
   #+BEGIN_SRC emacs-lisp
     (use-package yaml-mode
       :mode (
	      ("\\.yml\\'" . yaml-mode)
	      ("\\.yaml\\'" . yaml-mode))
       :config
       (add-hook 'yaml-mode-hook
	   '(lambda ()
	     (define-key yaml-mode-map "\C-m" 'newline-and-indent))))
   #+END_SRC

* Mode Line
  The mode line from Spacemacs
  [[https://github.com/TheBB/spaceline][GitHub Page]]
  #+BEGIN_SRC emacs-lisp
    (use-package spaceline
      :init
      (require 'spaceline-config)
      (setq spaceline-highlight-face-func 'spaceline-highlight-face-evil-state))

    (use-package spaceline-all-the-icons
      :after spaceline
      :config (spaceline-all-the-icons-theme))
  #+END_SRC

** Theme
   Spaceline All The Icons Theme
   [[https://github.com/domtronn/spaceline-all-the-icons.el][GitHub Page]]
   #+BEGIN_SRC emacs-lisp
   (use-package spaceline-all-the-icons
     :after (all-the-icons spaceline)
     :config (spaceline-all-the-icons-theme))
   #+END_SRC

* Version Control
** Packages
*** magit
    [[https://github.com/magit/magit][GitHub Page]]
    #+BEGIN_SRC emacs-lisp
    (use-package magit)
    #+END_SRC

**** Show vertical blame buffer by default
     #+BEGIN_SRC emacs-lisp
       (require 'magit)
       (setq magit-blame-echo-style 'margin)
     #+END_SRC

*** evil-magit
    [[https://github.com/emacs-evil/evil-magit][GitHub Page]]
    #+BEGIN_SRC emacs-lisp
    (use-package evil-magit)
    #+END_SRC

*** show line changes in buffer
    #+BEGIN_SRC emacs-lisp
      (use-package git-gutter
	:ensure t
	:config
	(global-git-gutter-mode +1)
	(custom-set-variables
	 '(git-gutter:modified-sign " ")
	 '(git-gutter:added-sign " ")
	 '(git-gutter:deleted-sign " "))

	(set-face-background 'git-gutter:modified "#d08770")
	(set-face-background 'git-gutter:added "#a3be8c")
	(set-face-background 'git-gutter:deleted "#vf616a"))
    #+END_SRC

* Projects
** projectile
   [[https://github.com/bbatsov/projectile][GitHub Page]]
   #+BEGIN_SRC emacs-lisp
   (use-package projectile)
   #+END_SRC

** Load direnv files
   #+BEGIN_SRC emacs-lisp
     (use-package direnv
       :config
       (direnv-mode))
   #+END_SRC

** Open neotree menu at project root
   I almost never want to open neotree in my current directory. Opening at the project level makes more sense.
   #+BEGIN_SRC emacs-lisp
   #+END_SRC

* Setup Dashboard
  #+BEGIN_SRC emacs-lisp
  (setq initial-buffer-choice "~/Documents/org/index.org")
  #+END_SRC

* Key Bindings
** Configuration
*** Reload Config
    #+BEGIN_SRC emacs-lisp
    (defun reload-init-file ()
      (interactive)
      (load-file "~/.emacs.d/init.el"))
    (evil-leader/set-key "r" 'reload-init-file)
    #+END_SRC

** Projects
   | Keys        | Function                    |
   |-------------+-----------------------------|
   | =SPC p t=   | =neotree-project-dir=       |
   | =SPC p f f= | =helm-projectile-find-file= |
   | =SPC p s=   | =helm-projectile-ag=        |
*** Define project prefix command
    We want =which-key= to give us useful options. Without defining a prefix command, the menu item for a prefix, will simply say =+prefix=.
    #+BEGIN_SRC emacs-lisp
    (define-prefix-command 'project)
    (which-key-add-key-based-replacements "SPC p" "project")
    (define-key evil-normal-state-map (kbd "SPC p") 'project)

    (define-prefix-command 'project-find)
    (which-key-add-key-based-replacements "SPC p f" "find")
    #+END_SRC

*** Key mappings
    Here we define a function that opens up neotree at the current project, then map that to ="SPC p t"=.
    #+BEGIN_SRC emacs-lisp
      (defun neotree-project-dir ()
	"Open NeoTree using the project root."
	(interactive)
	(let ((project-dir (projectile-project-root))
	      (file-name (buffer-file-name)))
	  (neotree-toggle)
	  (if project-dir
	      (if (neo-global--window-exists-p)
		  (progn
		    (neotree-dir project-dir)
		    (neotree-find file-name)))
	    (message "Could not find project root."))))
      (define-key evil-normal-state-map (kbd "SPC p t") 'neotree-project-dir)
      (define-key evil-normal-state-map (kbd "SPC p f f") 'helm-projectile-find-file)
      (define-key evil-normal-state-map (kbd "SPC p s") 'helm-projectile-ag)
    #+END_SRC

** LSP
*** Key Bindings
    | Keys      | Function                   |
    |-----------+----------------------------|
    | =, d=     | =lsp-find-definition=      |
    | =SPC l e= | =lsp-treemacs-errors-list= |
    #+TBLFM: $1=SPC l e

*** Define prefixes
    #+BEGIN_SRC emacs-lisp
      (define-prefix-command 'language-server)
      (define-key evil-normal-state-map (kbd "SPC l") 'language-server)
      ; (which-key-add-key-based-replacements "SPC l" "language-server")
    #+END_SRC
*** Define key bindings
    #+BEGIN_SRC emacs-lisp
      (define-key evil-normal-state-map (kbd ", d") 'lsp-find-definition)
      (define-key evil-normal-state-map (kbd "SPC l e") 'lsp-treemacs-errors-list)
    #+END_SRC

** Magit
*** Key Bindings
    | Keys        | Function                           |
    |-------------+------------------------------------|
    | =SPC g S=   | =magit-status=                     |
    | =SPC g s f= | =magit-stage-file=                 |
    | =SPC g c=   | =magit-commit=                     |
    | =SPC g P=   | =magit-push-current-to-pushremote= |
    | =SPC g b c= | =magit-branch-checkout=            |
    | =SPC g d u= | =magit-diff-unstaged=              |
    | =SPC g B=   | =magit-blame-echo=                 |
*** Define magit prefix command
    #+BEGIN_SRC emacs-lisp
    (define-prefix-command 'magit)
    (define-key evil-normal-state-map (kbd "SPC g") 'magit)

    (which-key-add-key-based-replacements "SPC g b" "branch")
    (which-key-add-key-based-replacements "SPC g d" "diff")
    (which-key-add-key-based-replacements "SPC g s" "stage")
    #+END_SRC

*** Define magit key bindings
    #+BEGIN_SRC emacs-lisp
    (define-key evil-normal-state-map (kbd "SPC g S") 'magit-status)
    (define-key evil-normal-state-map (kbd "SPC g s f") 'magit-stage-file)
    (define-key evil-normal-state-map (kbd "SPC g c") 'magit-commit)
    (define-key evil-normal-state-map (kbd "SPC g P") 'magit-push-current-to-pushremote)
    (define-key evil-normal-state-map (kbd "SPC g b c") 'magit-branch-checkout)
    (define-key evil-normal-state-map (kbd "SPC g d u") 'magit-diff-unstaged)
    (define-key evil-normal-state-map (kbd "SPC g B") 'magit-blame-echo)
    #+END_SRC

** neotree evil-mode compatibility
   #+BEGIN_SRC emacs-lisp
   (add-hook 'neotree-mode-hook
     (lambda ()
       (define-key evil-normal-state-local-map (kbd "TAB") 'neotree-enter)
       (define-key evil-normal-state-local-map (kbd "SPC") 'neotree-quick-look)
       (define-key evil-normal-state-local-map (kbd "q") 'neotree-hide)
       (define-key evil-normal-state-local-map (kbd "RET") 'neotree-enter)
       (define-key evil-normal-state-local-map (kbd "g") 'neotree-refresh)
       (define-key evil-normal-state-local-map (kbd "n") 'neotree-next-line)
       (define-key evil-normal-state-local-map (kbd "p") 'neotree-previous-line)
       (define-key evil-normal-state-local-map (kbd "A") 'neotree-stretch-toggle)
       (define-key evil-normal-state-local-map (kbd "H") 'neotree-hidden-file-toggle)))
   #+END_SRC

** eyebrowse
*** Key Bindings
    | Keys  | Function                       |
    |-------+--------------------------------|
    | =g t= | =eyebrowse-next-window-config= |
    | =g T= | =eyebrowse-prev-window-config= |
*** Define Key Bindings
    #+BEGIN_SRC emacs-lisp
      (define-key evil-normal-state-map (kbd "g t") 'eyebrowse-next-window-config)
      (define-key evil-normal-state-map (kbd "g T") 'eyebrowse-prev-window-config)
    #+END_SRC

* Editing
** Autoamtically remove trailing whitespace
   #+BEGIN_SRC emacs-lisp
     (add-hook 'before-save-hook 'delete-trailing-whitespace)
   #+END_SRC
